- name: 复制自定义sql文件
  copy:
    src: files/custom.sql
    dest: /tmp/custom.sql
    mode: 0777

- name: 执行自定义sql语句
  community.mysql.mysql_db:
    state: import
    name: "global_data"
    login_host: "{{ db_login_host }}"
    login_user: "{{ db_login_user }}"
    login_password: "{{ db_login_password }}"
    login_port: "{{ database_port }}"
    encoding: utf8mb4
    target: /tmp/custom.sql
  vars:
    ansible_python_interpreter: "/venv/bin/python3"
