- name: 创建.well-known目录
  file:
    path: /var/lib/letsencrypt/.well-known
    state: directory
    mode: 0777
    owner: nginx
    group: nginx
    recurse: yes
    force: no

- name: 创建snippets目录
  file:
    path: /etc/nginx/snippets
    state: directory
    mode: 0777
    recurse: yes
    force: no

- name: 上传letsencrypt.conf
  copy:
    src: files/letsencrypt.conf
    dest: /etc/nginx/snippets/letsencrypt.conf
    mode: 0666
    force: "{{ update_resource }}"

- name: 上传ssl.conf
  copy:
    src: files/ssl.conf
    dest: /etc/nginx/snippets/ssl.conf
    mode: 0666
    force: "{{ update_resource }}"


- name: 上传python requirements.txt 文件到服务器
  copy:
    src: files/requirements.txt
    dest: /datas/resource/requirements.txt
    mode: 0777
    force: "{{ update_resource }}"


- name: Install requirements
  pip:
    requirements: /datas/resource/requirements.txt
    virtualenv_command: "{{python3_interpreter_path}} -m venv"
    virtualenv: /venv


- name: Create 网站的数据库
  community.mysql.mysql_db:
    name: "{{ database_name }}"
    login_host: "{{ db_login_host }}"
    login_user: "{{ db_login_user }}"
    login_password: "{{ db_login_password }}"
    login_port: "{{ database_port }}"
    state: present
  vars:
    ansible_python_interpreter: "/venv/bin/python3"



- name: Create 全局数据的数据库
  community.mysql.mysql_db:
    name: "global_data"
    login_host: "{{ db_login_host }}"
    login_user: "{{ db_login_user }}"
    login_password: "{{ db_login_password }}"
    login_port: "{{ database_port }}"
    state: present
  vars:
    ansible_python_interpreter: "/venv/bin/python3"



- name: 创建mysql账号
  mysql_user:
    login_host: "{{ db_login_host }}"
    login_user: "{{ db_login_user }}"
    login_password: "{{ db_login_password }}"
    login_port: "{{ database_port }}"
    name: "{{ database_user }}"
    password: "{{ database_password }}"
    host: "localhost"
    priv: "{{ database_name }}.*:ALL,GRANT/global_data.*:ALL,GRANT"
    state: "present"
  vars:
    ansible_python_interpreter: "/venv/bin/python3"


- name: 创建图片共享目录
  file:
    path: "/datas/images"
    state: directory
    mode: 0777
    recurse: yes
    force: yes


- name: 创建nginx日志目录
  file:
    path: "/datas/logs/nginx"
    state: directory
    mode: 0777
    recurse: yes

- name: 删除已经存在的网站目录
  file:
    path: "/datas/www/{{ domain }}"
    state: absent

- name: 创建网站代码的目录
  file:
    path: "/datas/www/{{ domain }}"
    state: directory
    mode: 0777
    recurse: yes
    force: yes

- include_tasks: opencart.yaml
  when: cms_type == 'opencart'


- include_tasks: opencart2.yaml
  vars:
    admin_dir: "ourwebmag2018"
  when: cms_type == 'opencart_2'