- name: 创建存放代码的目录
  file:
    path: /datas/resource/opencart/
    state: directory
    mode: 0777
    recurse: yes


- name: 当load_data_online为yes的时候,线上下载安装包
  get_url:
    validate_certs: no
    url: "{{ cms_download_url }}"
    dest: /datas/resource/opencart/opencart_3.0.3.7.tar
    mode: 0755
    force: "{{ update_resource }}"
  when: load_data_online == 'yes'

- name: 当load_data_online为no的时候,上传安装包
  copy:
    src: files/opencart_3.0.3.7.tar
    dest: /datas/resource/opencart/
    mode: 0777
    force: "{{ update_resource }}"
  when: load_data_online == 'no'

- name: 解压下载tar包
  unarchive:
    src: /datas/resource/opencart/opencart_3.0.3.7.tar
    dest: "/datas/resource/opencart/"
    owner: apache
    group: apache
    mode: 0777
    copy: no

- name: 解压 opencart源码包
  unarchive:
    src: /datas/resource/opencart/opencart_3.0.3.7/opencart-3.0.3.7.tar.gz
    dest: "/datas/www/{{ domain }}"
    owner: apache
    group: apache
    mode: 0777
    copy: no


- name: install opencart cms
  opencart_install:
    database_user: "{{ database_user }}"
    database_password: "{{ database_password }}"
    database_name: "{{ database_name }}"
    database_port: "{{ database_port }}"
    opencart_admin_account: "{{ opencart_admin_account }}"
    opencart_admin_password: "{{ opencart_admin_password }}"
    opencart_admin_email: "{{ opencart_admin_email }}"
    opencart_db_prefix: "{{ opencart_db_prefix }}"
    domain: "{{ domain }}"
    dir_opencart: "/datas/www/{{ domain }}"
    db_driver: "{{ db_driver }}"
    sql_file_path: "/datas/resource/opencart/opencart_3.0.3.7/opencart3.0.3.7.sql"
  vars:
    ansible_python_interpreter: "/venv/bin/python3"


- name: 创建link图片目录
  file:
    src: "/datas/images"
    dest: "/datas/www/{{ domain }}/image/catalog/share_images"
    mode: 0777
    state: link


- name: 生成nginx 配置文件
  template:
    src: templates/site.conf
    dest: "/etc/nginx/conf.d/{{domain}}.conf"
    mode: '0644'
  vars:
    root_path: "/datas/www/{{domain}}"
    site_port: "{{nginx_site_port}}"
    server_name: "{{domain}}"
    nginx_fastcgi_pass: "{{ php_fastcgi_pass }}"

- name: 重新启动nginx
  service: name=nginx state=restarted


