- name: 复制管理目录
  copy:
    src: files/opencart2/admin/
    dest: /datas/www/{{domain}}/{{ admin_dir }}
    mode: 0777


- name: 复制catalog文件
  copy:
    src: files/opencart2/catalog/
    dest: /datas/www/{{domain}}/catalog
    mode: 0777

- name: 复制配置模板
  template:
    src: files/opencart2/custom_config.php
    dest: /datas/www/{{domain}}/{{ admin_dir }}/custom_config.php
    mode: 0755


